spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  profiles:
    active: development

output:
  ansi:
    enabled: always

instancio:
  bean:
    validation:
      enabled: true

sql:
  init:
    mode: always

logging:
  level:
    root: INFO

rsa:
  private-key: ${JWT_PRIVATE_KEY_PATH:classpath:certs/private.pem}
  public-key: ${JWT_PUBLIC_KEY_PATH:classpath:certs/public.pem}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
sentry:
  dsn: https://b0a218a90bd6e5ceac8d8ed783fce40a@o4509832734179328.ingest.de.sentry.io/4509832739094608
  traces-sample-rate: 1.0

