name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make script executable
        run: chmod +x gradlew
      - name: Write JWT keys
        run: |
          mkdir -p src/main/resources/certs
          printf "%s" "${{ secrets.JWT_PRIVATE_KEY }}" > src/main/resources/certs/private.pem
          printf "%s" "${{ secrets.JWT_PUBLIC_KEY }}"  > src/main/resources/certs/public.pem
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          cache-read-only: false
#      - run: ./gradlew checkstyleMain
      - run: ./gradlew test
        env:
          JWT_PRIVATE_KEY_PATH: ${{ secrets.JWT_PRIVATE_KEY_PATH }}
          JWT_PUBLIC_KEY_PATH: ${{ secrets.JWT_PUBLIC_KEY_PATH }}